### ISSUE TITLE
I can not find the class_balanced_loss file

### ISSUE THREAD

**Issue by yjtlab** [Harvard-Ophthalmology-AI-Lab/Harvard-GF#1]
I can not find the class_balanced_loss file, however, it is imported by train_glaucoma_fair_fin.py in line 23

**Comment by erikazhengyilin** [comment]
me too, how did you fixed it? I did just commented out that line as it seems like it isnt used but I just want to make sure

**Comment by luoyan407** [comment]
Thank you for your interest in this project.

Class-Balanced Loss is a compared method that was presented in CVPR'19 by a Google team. I have uploaded it to the folder src. 

Please let me know if you have any further questions.
